### ISSUE TITLE
Gleaner config created for new partners

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#89]
- Gleaner config (pointing to 4 new simple graph files, for 4 partners: **Indonesia**, **MASPAWIO**, **Benguela Current Commission**, **Caribbean Marine Atlas**): https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/gleaner-config-odis-simple-graph.yaml
  - (did not add AfricaMarineAtlas config yet, as waiting for meeting tomorrow/Tuesday discussing this catalogue status) cc @tchaddad
- also generated sitemaps for all of these 4 partners (that point to the GitHub-hosted JSON-LD files) 
  - Indonesia: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-ina-nodc/sitemap.xml
  - MASPAWIO: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-maspawio/sitemap.xml
  - Benguela Current Commission: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-benguelacc/sitemap.xml
  - Caribbean Marine Atlas: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-caribbeanmarineatlas/sitemap.xml
  
Related notes:
- all of these partner catalogues have been re-harvested live from their GeoNode endpoints through this process (meaning the JSON-LD files are accurate)
- I've forked the `gleaner` repo, and I aim to start using it and contributing someday ha!
- all of the above process is scripted and can be re-run easily

Here is a sample view of the Gleaner config
````
sources:
  - sourcetype: sitegraph
    name: inanodc
    logo: ""
    url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-ina-nodc/ina-nodc-simple-graph.json
    headless: false
    #pid: http://hdl.handle.net/1834/41372
    propername: "Indonesia National Oceanic Data Center"
    domain: https://geonode.nodc.id
    active: true
  - sourcetype: sitegraph
    name: maspawio
    logo: "https://cordioea.net/wp-content/uploads/2017/09/Geonde.png"
    url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-maspawio/maspawio-simple-graph.json
    headless: false
    #pid: http://hdl.handle.net/1834/41372
    propername: "MASPAWIO: Marine Spatial Atlas for the Western Indian Ocean"
    domain: http://maspawio.net
    active: true
  - sourcetype: sitegraph
    name: benguelacc
    logo: ""
    url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-benguelacc/benguelacc-simple-graph.json
    headless: false
    #pid: http://hdl.handle.net/1834/41372
    propername: "Benguela Current Convention (BCC) GeoData Portal"
    domain: https://geodata.benguelacc.org/
    active: true
  - sourcetype: sitegraph
    name: caribbeanmarineatlas
    logo: "https://www.caribbeanmarineatlas.net/static/cma2/landing_page/images/logotipo_CMA_2019.svg"
    url: https://raw.githubusercontent.com/iodepo/odis-arch/schema-dev-jm/code/notebooks/Exploration/data-caribbeanmarineatlas/caribbeanmarineatlas-simple-graph.json
    headless: false
    #pid: http://hdl.handle.net/1834/41372
    propername: "Caribbean Marine Atlas catalogue"
    domain: https://www.caribbeanmarineatlas.net/
    active: true  
```
